const members = [
    {
        name: 'John Smith',
        email: 'john.smith@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Jane Doe',
        email: 'jane.doe@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: ['CAD'],
        role: 'treasurer',
        isExec: true,
    },
    {
        name: 'Michael Johnson',
        email: 'michael.johnson@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: ['CAD', 'Engineering'],
        role: 'president',
        isExec: true,
    },
    {
        name: 'Emily Davis',
        email: 'emily.davis@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Christopher Brown',
        email: 'chris.brown@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: ['Engineering'],
        role: 'vice president',
        isExec: true,
    },
    {
        name: 'Jessica Taylor',
        email: 'jessica.taylor@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: ['Design', 'Marketing'],
        role: 'secretary',
        isExec: true,
    },
    {
        name: 'David Wilson',
        email: 'david.wilson@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Sarah Moore',
        email: 'sarah.moore@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Daniel White',
        email: 'daniel.white@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: ['Engineering'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Laura Harris',
        email: 'laura.harris@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Joshua Clark',
        email: 'joshua.clark@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: ['Design'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Sophia Lewis',
        email: 'sophia.lewis@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Matthew Hall',
        email: 'matthew.hall@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: ['Marketing'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Ashley Allen',
        email: 'ashley.allen@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Andrew Young',
        email: 'andrew.young@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Olivia King',
        email: 'olivia.king@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'James Scott',
        email: 'james.scott@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Abigail Martinez',
        email: 'abigail.martinez@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: ['Operations'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Ethan Garcia',
        email: 'ethan.garcia@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Mia Robinson',
        email: 'mia.robinson@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Benjamin Walker',
        email: 'benjamin.walker@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: ['Marketing'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Isabella Perez',
        email: 'isabella.perez@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Elijah Adams',
        email: 'elijah.adams@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Madison Baker',
        email: 'madison.baker@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: ['CAD'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Lucas Gonzalez',
        email: 'lucas.gonzalez@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Ava Nelson',
        email: 'ava.nelson@gatech.edu',
        teamMembership: 'CAD',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'William Carter',
        email: 'william.carter@gatech.edu',
        teamMembership: 'Engineering',
        teamsAdvising: ['Design'],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Emma Lee',
        email: 'emma.lee@gatech.edu',
        teamMembership: 'Design',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Alexander Evans',
        email: 'alexander.evans@gatech.edu',
        teamMembership: 'Marketing',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    },
    {
        name: 'Amelia Green',
        email: 'amelia.green@gatech.edu',
        teamMembership: 'Operations',
        teamsAdvising: [],
        role: 'member',
        isExec: false,
    }
];

export default members;